DELETE FROM Album;
DBCC CHECKIDENT (Album, RESEED, 0);

SET IDENTITY_INSERT [dbo].[Album] ON
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (1, 1, N'Kid A', N'638058485179546128.jfif', 100000, 5, N'Kid A is the fourth studio album by the English rock band Radiohead, released on 2 October 2000 by Parlophone. It was recorded with their producer, Nigel Godrich, in Paris, Copenhagen, Gloucestershire and Oxfordshire.')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (2, 1, N'OK Computer', N'638058489004609070.jfif', 50000, 25, N'OK Computer is the third studio album by the English rock band Radiohead, released in the UK on 16 June 1997 by EMI.')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (3, 2, N'The Bends', N'638058554486609538.jfif', 150000, 10, N'The Bends is the second studio album by the English rock band Radiohead, released on 13 March 1995 by Parlophone. It was produced by John Leckie, with extra production by Radiohead, Nigel Godrich and Jim Warren.')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (4, 2, N'Hail to the Thief', N'638059446432559006.jfif', 200000, 20, N'Hail to the Thief is the sixth studio album by the English rock band Radiohead. It was released on 9 June 2003 through Parlophone internationally and a day later through Capitol Records in the United States.')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (5, 3, N'A Moon Shaped Pool', N'638059447901481658.jfif', 250000, 15, N'A Moon Shaped Pool is the ninth studio album by the English rock band Radiohead. It was released digitally on 8 May 2016, and physically on 17 June 2016 through XL Recordings. ')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (6, 4, N'Pablo Honey', N'638059450808002463.jfif', 300000, 10, N'Pablo Honey is the debut studio album by the English rock band Radiohead, released on 22 February 1993 in the UK by Parlophone and on 20 April in the US by Capitol Records.')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (7, 5, N'In Rainbows', N'638058485179546128.jfif', 50000, 15, N'In Rainbows is the seventh studio album by the English rock band Radiohead. It was self-released on 10 October 2007 as a pay-what-you-want download.')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (8, 6, N'The King of Limbs', N'638058489004609070.jfif', 100000, 10, N'The King of Limbs is the eighth studio album by the English rock band Radiohead.')
INSERT INTO [dbo].[Album] ([AlbumID], [ArtistID], [AlbumName], [AlbumImage], [AlbumPrice], [AlbumStock], [AlbumDescription]) VALUES (9, 6, N'Amnesiac', N'638058554486609538.jfif', 150000, 20, N'Amnesiac is the fifth studio album by the English rock band Radiohead, released on 30 May 2001 by EMI subsidiaries Parlophone and Capitol Records.')
SET IDENTITY_INSERT [dbo].[Album] OFF
